version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: world
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - "./data:/docker-entrypoint-initdb.d" # sync db data with container db data
    ports:
      - "3306:3306"

  website:
    build: ./src
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    restart: on-failure

    command: npm run start