version: 2.1

jobs:
  test-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          docker-compose up -d
          
          docker-compose down

workflows:
  docker_compose_up:
    jobs:
      - test-docker