version: 2.1
orbs:
  node: circleci/node@5.2.0
  
jobs:
  test-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          npx mocha src/student.test.js

workflows:
  docker_compose_up:
    jobs:
      - test-docker