version: 2.1
  
jobs:
  test-docker:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build
          command: docker-compose build
      - run: 
          name: Start container
          command: docker-compose up -d
      - run:
          name: Stop container
          command: docker-compose down

workflows:
  version: 2
  build:
    jobs:
      - test-docker